spring:
  thymeleaf:
    suffix: .html
    prefix: classpath:/templates/
  datasource:
    url: jdbc:mariadb://192.168.219.101:43306/minicampus
    driver-class-name: org.mariadb.jdbc.Driver
    username: minicampus_user
    password: a1234

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
